language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false
script:
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("BayesianTools"); Pkg.test("BayesianTools"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BayesianTools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
